<?php

use Livewire\Component;
use Livewire\Attributes\Title;

new #[Title('New Chat')] class extends Component
{
    public string $prompt = '';

    public bool $hasMessages = false;

    // Generated by Claude
    public string $sampleMarkdownOutput = <<<EOF
        # Welcome to LaravelAI
        This is a **bold statement** and this is *italic text*. Here's some `inline code` too.

        ## Features

        - Real-time streaming responses
        - Multiple AI providers via **Prism**
    EOF;
};