<?php

use Livewire\Component;
use Livewire\Attributes\Title;
use Livewire\Attributes\Computed;

new #[Title('New Chat')] class extends Component
{
    public string $prompt = '';

    public $selectedModel = '';

    public bool $hasMessages = false;

    public function mount(): void
    {
        $this->selectedModel = config('ai.models')[config('ai.model')]['api_name'];
    }

    /**
     * Get all available AI models from config.
     *
     * @return array<string, array{name: string, provider: string, description: string}>
     */
    #[Computed]
    public function availableModels(): array
    {
        return config('ai.models');
    }

    // Generated by Claude
    public string $sampleMarkdownOutput = <<<EOF
        # Welcome to LaravelAI
        This is a **bold statement** and this is *italic text*. Here's some `inline code` too.

        ## Features

        - Real-time streaming responses
        - Multiple AI providers via **Prism**
    EOF;
};